In [2]:
import pandas as pd
train_df = pd.read_csv("NSLKDD_top_10_TRAIN.csv")
test_df = pd.read_csv("NSLKDD_top_10_TEST.csv")

In [3]:
train_df

,same_srv_rate,dst_host_srv_serror_rate,dst_host_serror_rate,serror_rate,srv_serror_rate,dst_host_srv_count,dst_host_same_srv_rate,logged_in,flag,count,attack
0,0.08,0.00,0.00,0.0,0.0,1,0.00,0,9,13,1
1,0.05,1.00,1.00,1.0,1.0,26,0.10,0,5,123,0
2,1.00,0.01,0.03,0.2,0.2,255,1.00,1,9,5,1
3,1.00,0.00,0.00,0.0,0.0,255,1.00,1,9,30,1
4,0.16,0.00,0.00,0.0,0.0,19,0.07,0,1,121,0
...,...,...,...,...,...,...,...,...,...,...,...
125967,0.14,1.00,1.00,1.0,1.0,25,0.10,0,5,184,0
125968,1.00,0.00,0.00,0.0,0.0,244,0.96,0,9,2,1
125969,1.00,0.00,0.72,0.0,0.0,30,0.12,1,9,1,1
125970,0.06,1.00,1.00,1.0,1.0,8,0.03,0,5,144,0
125971,1.00,0.00,0.00,0.0,0.0,77,0.30,1,9,1,1

In [4]:
test_df

,same_srv_rate,dst_host_srv_serror_rate,dst_host_serror_rate,serror_rate,srv_serror_rate,dst_host_srv_count,dst_host_same_srv_rate,logged_in,flag,count,attack
0,0.01,0.0,0.00,0.0,0.00,1,0.00,0,1,136,0
1,1.00,0.0,0.00,0.0,0.00,86,0.61,0,9,1,1
2,1.00,0.0,0.00,0.0,0.00,57,1.00,0,9,1,2
3,1.00,0.0,0.00,0.0,0.12,86,0.31,0,2,1,2
4,1.00,0.0,0.01,0.0,0.00,255,1.00,1,9,4,1
...,...,...,...,...,...,...,...,...,...,...,...
22538,1.00,0.0,0.01,0.0,0.00,141,0.72,1,9,1,1
22539,1.00,0.0,0.01,0.0,0.00,255,1.00,1,9,2,1
22540,1.00,0.0,0.00,0.0,0.00,255,1.00,1,9,5,0
22541,1.00,0.0,0.00,0.0,0.00,252,0.99,0,9,4,1
22542,0.25,0.0,0.00,0.0,0.00,21,0.08,0,1,4,2

In [5]:
train_x = train_df.drop(labels=['attack'],axis=1)
train_y = train_df['attack']
train_x

,same_srv_rate,dst_host_srv_serror_rate,dst_host_serror_rate,serror_rate,srv_serror_rate,dst_host_srv_count,dst_host_same_srv_rate,logged_in,flag,count
0,0.08,0.00,0.00,0.0,0.0,1,0.00,0,9,13
1,0.05,1.00,1.00,1.0,1.0,26,0.10,0,5,123
2,1.00,0.01,0.03,0.2,0.2,255,1.00,1,9,5
3,1.00,0.00,0.00,0.0,0.0,255,1.00,1,9,30
4,0.16,0.00,0.00,0.0,0.0,19,0.07,0,1,121
...,...,...,...,...,...,...,...,...,...,...
125967,0.14,1.00,1.00,1.0,1.0,25,0.10,0,5,184
125968,1.00,0.00,0.00,0.0,0.0,244,0.96,0,9,2
125969,1.00,0.00,0.72,0.0,0.0,30,0.12,1,9,1
125970,0.06,1.00,1.00,1.0,1.0,8,0.03,0,5,144
125971,1.00,0.00,0.00,0.0,0.0,77,0.30,1,9,1

In [6]:
test_x = test_df.drop(labels=['attack'],axis=1)
test_y = test_df['attack']
test_x

,same_srv_rate,dst_host_srv_serror_rate,dst_host_serror_rate,serror_rate,srv_serror_rate,dst_host_srv_count,dst_host_same_srv_rate,logged_in,flag,count
0,0.01,0.0,0.00,0.0,0.00,1,0.00,0,1,136
1,1.00,0.0,0.00,0.0,0.00,86,0.61,0,9,1
2,1.00,0.0,0.00,0.0,0.00,57,1.00,0,9,1
3,1.00,0.0,0.00,0.0,0.12,86,0.31,0,2,1
4,1.00,0.0,0.01,0.0,0.00,255,1.00,1,9,4
...,...,...,...,...,...,...,...,...,...,...
22538,1.00,0.0,0.01,0.0,0.00,141,0.72,1,9,1
22539,1.00,0.0,0.01,0.0,0.00,255,1.00,1,9,2
22540,1.00,0.0,0.00,0.0,0.00,255,1.00,1,9,5
22541,1.00,0.0,0.00,0.0,0.00,252,0.99,0,9,4
22542,0.25,0.0,0.00,0.0,0.00,21,0.08,0,1,4

In [7]:
from sklearn.neighbors import KNeighborsClassifier as knn
knn_clf = knn()
knn_clf.fit(train_x,train_y)

KNeighborsClassifier()

In [8]:
from sklearn.metrics import classification_report,accuracy_score
ypred = knn_clf.predict(test_x)
print(classification_report(test_y,ypred))

              precision    recall  f1-score   support

           0       0.85      0.66      0.74      7459
           1       0.61      0.92      0.74      9711
           2       0.59      0.52      0.56      2421
           3       0.52      0.02      0.04      2885
           4       0.00      0.00      0.00        67

    accuracy                           0.67     22543
   macro avg       0.52      0.42      0.41     22543
weighted avg       0.68      0.67      0.63     22543

/Users/chavamanish/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/chavamanish/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/chavamanish/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [9]:
print(accuracy_score(test_y,ypred))

0.6722264117464402